
# html lang
language: cn

# main menu navigation
menu:
  home:
    path: /
    name: "首页"
  categories:
    path: /categories
    name: "分类"
  tags:
    path: /tags
    name: "标签"
  archives:
    path: /archives
    name: "归档"
  about:
    path: /about
    name: "关于"

# stylesheets loaded in the <head>
stylesheets:
- /css/onepisces.css

# scripts loaded in the end of the body
scripts:
- /js/onepisces.js

# valine评论系统：valine.js.org
valine:
  enable: true
  appID: 'rVJdla4iZQeE8zD3UX0W2NO2-gzGzoHsz'
  appKey: 'Komh0dST8Uw6KFjAP7CpCb7Y'
  placeholder: '发条评论吧'
  pageSize: 10
  visitor: true
  recordIP: true
  enableQQ: false
